### ISSUE TITLE
嚴重問題: 執行緒互搶螢幕顏色資源導致死亡

### ISSUE THREAD

**Issue by josh-hsu** [josh-hsu/JoshAutomationFX#5]
Log:

2017/12/04 下午 03:52:48: [FATL] LibGame: !!!FATAL EXCEPTION!!! index out of bound, content: sum 0
java.lang.ArrayIndexOutOfBoundsException: 2
	at com.mumu.libjoshgame.CaptureService.getColorOnDump(CaptureService.java:170)
	at com.mumu.libjoshgame.CaptureService.getColorOnDumpInternal(CaptureService.java:144)
	at com.mumu.libjoshgame.CaptureService.getColorOnScreen(CaptureService.java:211)
	at com.mumu.libjoshgame.CaptureService.colorIs(CaptureService.java:798)
	at com.mumu.joshautomation.ro.RORoutine.isHPLowerThan(RORoutine.java:68)
	at com.mumu.joshautomation.ro.RORoutine.isInBattleMode(RORoutine.java:90)
	at com.mumu.joshautomation.ro.ROAutoRoutineJob$ROJobRoutine.main(ROAutoRoutineJob.java:196)
	at com.mumu.joshautomation.ro.ROAutoRoutineJob$ROJobRoutine.run(ROAutoRoutineJob.java:216)

**Comment by josh-hsu** [comment]
已在版本 2645717cf9b880c06cba9e6f2f8b753653ddfcf5
解掉此問題，等待驗證後關閉
